---
title: "Combining the Training and Testing Data"
author: "Sean Hughes"
date: "30-5-2020"
output: 
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes 
    toc_float: yes
---

```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```


# Load the necessary packages

```{r}
library(ggthemes)
library(foreign)
library(tidyverse)
library(Hmisc)
library(car)
library(readxl)
library(ggplot2)
library(dplyr)
library(xlsx)
```

## 1. Import the raw data files from Excel into R

```{r}

wd <- list()
wd$data   <- "C:/Users/Sean/Desktop/Intersecting_Regularties_/Study 5/Raw_Data/"
wd$output <- "C:/Users/Sean/Desktop/Intersecting_Regularties_/Study 5/Processed_Data/"

raw_data_1 <- read_csv2(paste0(wd$output, "Study_5_Training_Phase.csv"), col_names = TRUE)
raw_data_2 <- read_csv2(paste0(wd$output, "Study_5_Test_Phase_1.csv"), col_names = TRUE)
raw_data_3 <- read_csv2(paste0(wd$output, "Study_5_Counterconditioning_Phase.csv"), col_names = TRUE)
raw_data_4 <- read_csv2(paste0(wd$output, "Study_5_Test_Phase_2.csv"), col_names = TRUE)

# Order of the Experiment: 
# 1. Intersecting Regularities Training
# 2. Acquisition Phase Test (i.e., test if people learned anything during the training phase)
# 3. Counterconditioning Phase
# 4. Counterconditioning Phase Test (i.e., to see if people learned anything during the Counterconditioning phase)


```

## 2. Join the files together

```{r}

processed_data <- raw_data_1 %>% 
  bind_rows(raw_data_2, raw_data_3, raw_data_4) %>%
  select(-block_number) %>%
  arrange(subject, block_type) 

# Create file with information indicating if people were in the acquisition only or Counterconditioning groups, and if they passed or failed the initial training phase 

 experimental_condition <- processed_data %>%
   group_by(subject) %>%
   mutate(experimental_condition = ifelse(block_type == "Counterconditioning", "CC", "AQ")) %>%
   select(subject, training_performance, experimental_condition)
   
 experimental_condition[duplicated(experimental_condition$subject), ]

 experimental_condition <- experimental_condition[!duplicated(experimental_condition$subject), ]
 

```

## 3. Calculate number of people in the different experimental conditions as a function of Fail vs. Pass 

```{r}

# Calculate mean and SD for accuracy (i.e., the correct row) 

Final_data <- processed_data %>% 
  group_by(block_type, training_performance) %>% 
  summarise(group_number = n(), mean_accuracy = mean(mean_correct))

```


## 7. Graph accuracy across blocks for those who passed vs. failed

```{r}

# Covert Block Type to a factor and order the levels sequentially (i.e., from Training to Test_2)

Final_data$block_type = as.factor(Final_data$block_type)
Final_data$block_type <- ordered(Final_data$block_type, levels = c("Training", "Test_1", "Counterconditioning", "Test_2"))

# Graph Mean and SD accuracy across blocks

ggplot(Final_data, aes(x=block_type, y=mean_accuracy, fill = training_performance)) +
    geom_bar(colour="black", stat="identity", position = position_dodge()) + theme_classic()

```


##8. Write Data to File

```{r}

write_csv2(as.data.frame(experimental_condition), path = paste0(wd$output, "Study_5_Complete_Training_Testing_Data.csv"))

```

