---
title: "Study 1: Testing Phase (after Acquisition Phase)"
author: "Sean Hughes & Ian Hussey"
date: 
output: 
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes 
    toc_float: yes
---

```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```


# Load the necessary packages

```{r}
library(tidyverse)
library(readxl)
library(ggthemes)
library(knitr)
library(kableExtra)
```

# Import the raw data files from Excel into R

```{r}

data_input <- 
  # read in data, appending a new column
  bind_rows(
    read_xlsx("raw/testing_left_17_03_17.xlsx", col_names = TRUE),
    read_xlsx("raw/testing_left_rev_17_03_17.xlsx", col_names = TRUE),
    read_xlsx("raw/testing_right_17_03_17.xlsx", col_names = TRUE),
    read_xlsx("raw/testing_right_rev_17_03_17.xlsx", col_names = TRUE)) %>%
  
  # add in information that indicates the experiment 
  mutate(experiment = 1) %>%
  
  # remove redundant information
  filter(blockcode != "Begin") %>% 

  # select and rename variables
  select(experiment, subject, trial_number = trialnum, correct) %>%
  arrange(subject)

```

# Completeness

```{r}

data_completeness <- data_input %>%
  group_by(subject) %>%
  mutate(complete_data = ifelse(sum(trial_number) == 36, "complete", 
                                ifelse(sum(trial_number) > 36, "excess", "partial"))) %>%
  ungroup()

data_completeness %>%
  distinct(subject, .keep_all = TRUE) %>%
  count(complete_data) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

data_completeness_by_participant <- data_completeness %>%
  distinct(subject, complete_data)

```

# Performance

```{r}

data_performance <- data_completeness %>%
  # summarize performance by block
  group_by(subject) %>% 
  summarise(mean_correct = mean(correct), 
            sd_correct = sd(correct)) %>%
  mutate(training_performance = ifelse(mean_correct < .70, "Fail", "Pass")) %>%
  ungroup() 


# plot
data_performance %>% 
  group_by(training_performance) %>% 
  summarise(mean_accuracy = mean(mean_correct), sd_accuracy = sd(sd_correct)) %>%
  ggplot(aes(x=training_performance, y=mean_accuracy)) +
  geom_bar(colour="black", stat="identity", position = position_dodge()) + 
  geom_errorbar(aes(ymin=mean_accuracy-sd_accuracy, ymax=mean_accuracy+sd_accuracy), width=.2,
                position=position_dodge(.9)) + theme_classic()


```

## Combine and write to disk

```{r}
#Write data back to disk in csv format.

data_testing_phase_1 <- 
  full_join(data_performance, 
            data_completeness_by_participant, 
            by = "subject")

write_csv2(data_testing_phase_1, "processed/data_testing_phase_1.csv")

```



