---
title: "Study 1: Extinction Phase"
subtitle: "Data processing"
author: "Sean Hughes & Ian Hussey"
date: "30-5-2020"
output: 
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes 
    toc_float: yes
---

```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```


# Dependencies

```{r}
library(tidyverse)
library(readxl)
library(ggthemes)
library(knitr)
library(kableExtra)
```

## get data

```{r}

data_input <- 
  bind_rows(
    read_xlsx("raw/extinction1a_intersecting_regularities_left_17_03_17.xlsx"),
    read_xlsx("raw/extinction1a_intersecting_regularities_left_rev_17_03_17.xlsx"),
    read_xlsx("raw/extinction1a_intersecting_regularities_right_17_03_17.xlsx"),
    read_xlsx("raw/extinction1a_intersecting_regularities_right_rev_17_03_17.xlsx")
  ) %>%
  mutate(experiment = 1,
         training_condition = "Extinction") %>%
  filter(blockcode != "Begin") %>% 
  # select and rename vars
  select(subject, experiment, block_number = blocknum, trial_number = trialnum, correct) %>%
  arrange(subject)

```

# Completeness

```{r}

data_completeness <- data_input %>%
  group_by(subject) %>%
  mutate(complete_data = ifelse(sum(block_number) == 200, "complete", 
                                ifelse(sum(block_number) > 200, "excess", "partial"))) %>%
  ungroup()

data_completeness %>%
  distinct(subject, .keep_all = TRUE) %>%
  count(complete_data) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

data_completeness_by_participant <- data_completeness %>%
  distinct(subject, stimulus_identity, complete_data)

```

# Performance

```{r}

# Calculate mean and SD for accuracy (i.e., the correct row) 

data_performance <- data_completeness %>%
  # summarize performance by block
  group_by(subject, block_number) %>% 
  summarise(mean_correct = mean(correct), 
            sd_correct = sd(correct)) %>%
  mutate(training_performance_by_block = ifelse(mean_correct < .70, "Fail", "Pass")) %>%
  ungroup() %>% 
  # summarize performance by participant (final block only)
  group_by(subject) %>% 
  mutate(training_performance = ifelse(block_number == 5 & training_performance_by_block == "Pass", "Pass", "Fail")) %>%
  ungroup() %>%
  arrange(subject, block_number)

# plot
data_performance %>% 
  group_by(block_number, training_performance_by_block) %>% 
  summarise(mean_accuracy = mean(mean_correct), sd_accuracy = sd(sd_correct)) %>%
  ggplot(aes(x=block_number, y=mean_accuracy, fill = training_performance_by_block)) +
  geom_bar(colour="black", stat="identity", position = position_dodge()) + 
  geom_errorbar(aes(ymin=mean_accuracy-sd_accuracy, ymax=mean_accuracy+sd_accuracy), width=.2,
                position=position_dodge(.9)) + theme_classic()


data_performance_by_participant <- data_performance %>%
  filter(block_number == 5) %>%
  select(-block_number, -training_performance_by_block)

```

# Combine and write to disk

```{r}

data_extinction_phase <- 
  full_join(data_completeness_by_participant, 
            data_performance_by_participant, 
            by = "subject")

write_csv2(data_extinction_phase, "processed/data_extinction_phase.csv")

```


