---
title: "Study 4: Extinction Phase"
author: "Sean Hughes"
date: "30-5-2020"
output: 
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes 
    toc_float: yes
---

```{r include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```


# Load the necessary packages

```{r}
library(foreign)
library(tidyverse)
library(Hmisc)
library(car)
library(readxl)
library(ggthemes)
library(xlsx)
```

## 1. Import the raw data files from Excel into R

```{r}

wd <- list()
wd$data   <- "C:/Users/Sean/Desktop/Intersecting_Regularties_/Study 4/Raw_Data/"
wd$output <- "C:/Users/Sean/Desktop/Intersecting_Regularties_/Study 4/Processed_Data/"

raw_data_1 <- read_xlsx(paste0(wd$data, "extinction_intersecting_regularities_1d_17_04_13.xlsx"), col_names = TRUE)

```

## 2. Join the training files together

```{r}

processed_data_1 <- raw_data_1 %>% 
  filter(blockcode != "Begin") %>% 
  select(subject, blocknum, trialnum, correct)

combined_data <- processed_data_1 %>%
  rename(block_number = blocknum, trial_number = trialnum) %>% 
  arrange(subject)

```

## 3. Exclude incomplete data

```{r}

# Number of participants before exclusions

Participants_before_exclusions <- combined_data %>% 
  distinct(subject) %>% 
  count()

# Check to see if everyone has complete data for the four training blocks - if block_number = 280 then they do. Otherwise they do not. If they do not then remove them 

combined_data <- combined_data %>%
  group_by(subject) %>% 
  mutate(complete_data_check = sum(block_number)) %>%
  filter(complete_data_check == 200) %>%
  ungroup() 

# Number of participants post exclusions

Participants_after_exclusions <- combined_data %>% 
  distinct(subject) %>% 
  count()


```

## 8. Merge the datasets

```{r}
#Write data back to disk in csv format.

combined_data <- combined_data %>% 
  distinct(subject) %>% 
  mutate(training_condition = "Extinction")
  

write_csv2(combined_data, path = paste0(wd$output, "Study_4_Extinction_Phase.csv"))


```



